apiVersion: traefik.io/v1alpha1
kind: MiddlewareTCP
metadata:
  name: postgres-ip-whitelist
  namespace: db
spec:
  ipAllowList:
    sourceRange:
    #   - "57.132.147.228/32"   # Your laptop IP
    # #   - "162.120.185.242/32"
    #   - "198.58.124.0/24"   # Optional office/network range
      - "198.58.121.98/32"  #Laod balancer IP in case to connect using LB IP only
      - "10.0.0.0/8"  # Internal k8s network range
      - "23.239.27.239/32"
      - "66.228.53.98/32"
